# Generated by Django 5.0.7 on 2024-07-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('first_login', models.DateField()),
                ('last_login', models.DateField()),
                ('level', models.PositiveIntegerField(default=0)),
                ('exp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('end_at', models.DateTimeField(default=None)),
                ('exp_multiplier', models.PositiveIntegerField(default=0)),
                ('exp_take', models.PositiveIntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_1.player')),
            ],
        ),
    ]
