# Generated by Django 5.0.7 on 2024-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='boost',
            name='end_at',
            field=models.DateTimeField(),
        ),
    ]
